config/routes.rb
Rails.application.routes.draw do

  # Home
  get '/home', to: 'home#welcome'

  # Admin
  match 'admin/filter/client', to: 'admin/filter#client_filter', via: [:get, :post]
  match 'admin/filter/cleaner', to: 'admin/filter#cleaner_filter', via: [:get, :post]

  # Registration
  get '/registration/client', to: 'registration#for_client'
  post '/registration/client', to: 'registration#create_client'
  get '/registration/cleaner', to: 'registration#for_cleaner'
  post '/registration/cleaner', to: 'registration#create_cleaner'
  
  # Login
  get '/login/client', to: 'sessions#for_client' 
  post '/login/client', to: 'sessions#create_client'
  get '/login/cleaner', to: 'sessions#for_cleaner' 
  post '/login/cleaner', to: 'sessions#create_cleaner'
  
  # Logout
  get '/logout_client', to: 'sessions#destroy_client'
  get '/logout_cleaner', to: 'sessions#destroy_cleaner'

  # Client Page
  get '/client/page', to: 'clients#page', as: :client_page
  get '/cleaner/page', to: 'cleaners#page', as: :cleaner_page
  
  # Client Delete
  delete '/client/delete', to: 'clients#destroy'
  
  #Cleaner Delete
  delete '/cleaner/delete', to: 'cleaners#destroy'

  # Client Edit 
  get '/cleaner/edit', to: 'cleaners#edit'
  post '/cleaner/edit', to: 'cleaners#update'

  #Cleaner Edit
  get '/client/edit', to: 'clients#edit'
  post '/client/edit', to: 'clients#update'
  
  # Client Booking
  get '/client/booking', to: 'bookings#book'
  post '/client/booking/check_cleaner', to: 'bookings#check_cleaner'
  post '/client/booking', to: 'bookings#create'
  

  # Cleaner Bookings
  get 'cleaner/bookings', to: 'cleaners#bookings'
  post '/cleaner/booking/:id', to: 'bookings#show', as: :cleaner_booking
  
  #Client Bookings
  get 'client/bookings', to: 'clients#bookings'

  #Cleaner edit password
  get 'cleaner/edit/password', to: 'cleaners#edit_password'
  post 'cleaner/edit/password', to: 'cleaners#change_password'

  #Client edit password
  get 'client/edit/password', to: 'clients#edit_password'
  post 'client/edit/password', to: 'clients#change_password'

  #Cleaner edit city
  match 'cleaner/edit/city', to: 'cleaners#edit_city', via: [:get, :post]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/booking.rb
class Booking < ApplicationRecord

  belongs_to :cleaner
  belongs_to :client
  belongs_to :city
  validates :date, uniqueness: {scope: :cleaner_id}

  def date_to_s
  	day = self.date.day > 9 ? self.date.day.to_s : '0' + self.date.day.to_s
  	month = self.date.month > 9 ? self.date.month.to_s : '0' + self.date.month.to_s 
  	year = self.date.year.to_s
  	day + '.' + month + '.' + year 
  end


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :authorize
  

  def book 
    @options = City.all.map { |city| [city.name, city.id] }
    puts '#' * 100
    # puts p request
    puts '#' * 100
  end

  def check_cleaner

    if /[0-9][0-9]\.[0-9][0-9]\.201[0-9]/ =~ params[:date]
      session[:date] = params[:date]
      session[:city_id] = params[:city] 
    else
      @notice = ['invalid data format!', 'exemple of format "01.01.2017"']
      @options = City.all.map { |city| [city.name, city.id] }
      render 'book.html.erb'
    end
    

     
    cleaners = City.find_by_id(params[:city].to_i).cleaners 

    valid_cleaners = []
    cleaners.each_with_index do |cleaner, i|
      valid = true
      cleaner.bookings.each do |cleaner| 
        if cleaner.date_to_s == session[:date]
          valid = false
          break
        end
      end
      valid_cleaners << cleaners[i] if valid
    end

    if valid_cleaners.empty?
      @notice = "no free cleaners on #{session[:date]}"
    else     
      @options = valid_cleaners.map { |cleaner| [cleaner.fname, cleaner.id] } 
    end

  end
  
  def create
    d = session[:date].split('.').map { |param| param.to_i }
    date = Date.new(d[2], d[1], d[0]) 
    t = Time.now
    time = "#{t.day}.#{t.month}.#{t.year} _ #{t.hour}:#{t.min}:#{t.sec}"
    booking = Booking.new({
                            client_id: session[:client_id], 
                            cleaner_id: params[:cleaner_id],
                            city_id: session[:city_id],
                            date: date,
                            time: time
                          })
    session[:date] = nil
    session[:city_id] = nil
    if booking.save
      redirect_to client_bookings_path 
    end
  end

  def destroy 
    booking = Booking.find_by_id params[:id]
    booking.destroy
  end

  def show
    @booking = Booking.find_by_id(params[:id])
    @booking.update read: true
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/book.html.erb
   

    <%= form_tag client_booking_check_cleaner_path, method: :post do %>
    <h1>Booking</h1>
      
      <%= label_tag 'Check city:', nil, class: :lab %>
      <%= select_tag 'city', options_for_select(@options), class: :sel %> 
      <%= label_tag 'Input date:' %>
      <%= text_field_tag 'date' %> 
      <%= submit_tag 'Check Cleaner' %>  

      <% if @notice %>
        <div class="err">
          <% @notice.each do |err|%>
            <%= err %><br>
          <% end %>
        </div>
      <% end %>

    <% end %>
    
    
    
  

  

app/views/bookings/check_cleaner.html.erb
  <%= form_tag client_booking_path, method: :post do %>

    <% if @notice %>
      <div class="err">
        <%= @notice %>
      </div>
    <% end %>
  <h2>Check Cleaner</h2>
    
    <%= select_tag 'cleaner_id', options_for_select(@options), class: :sel %>
	<%= submit_tag :Order %>
  
<% end %>

app/views/bookings/show.html.erb
<h1>Booking Show</h1>

<p>Client Fname: <%= @booking.client.fname %></p>
<p>Client Lname: <%= @booking.client.lname %></p>
<p>City: <%= @booking.city.name %></p>
<p>Date: <%= @booking.date_to_s %></p>
<p>Time: <%= @booking.time %></p>

<%= link_to "Back", cleaner_bookings_path %>