config/routes.rb
Rails.application.routes.draw do

  # Home
  get '/home', to: 'home#welcome'

  # Admin
  match 'admin/filter/client', to: 'admin/filter#client_filter', via: [:get, :post]
  match 'admin/filter/cleaner', to: 'admin/filter#cleaner_filter', via: [:get, :post]

  # Registration
  get '/registration/client', to: 'registration#for_client'
  post '/registration/client', to: 'registration#create_client'
  get '/registration/cleaner', to: 'registration#for_cleaner'
  post '/registration/cleaner', to: 'registration#create_cleaner'
  
  # Login
  get '/login/client', to: 'sessions#for_client' 
  post '/login/client', to: 'sessions#create_client'
  get '/login/cleaner', to: 'sessions#for_cleaner' 
  post '/login/cleaner', to: 'sessions#create_cleaner'
  
  # Logout
  get '/logout_client', to: 'sessions#destroy_client'
  get '/logout_cleaner', to: 'sessions#destroy_cleaner'

  # Client Page
  get '/client/page', to: 'clients#page', as: :client_page
  get '/cleaner/page', to: 'cleaners#page', as: :cleaner_page
  
  # Client Delete
  delete '/client/delete', to: 'clients#destroy'
  
  #Cleaner Delete
  delete '/cleaner/delete', to: 'cleaners#destroy'

  # Client Edit 
  get '/cleaner/edit', to: 'cleaners#edit'
  post '/cleaner/edit', to: 'cleaners#update'

  #Cleaner Edit
  get '/client/edit', to: 'clients#edit'
  post '/client/edit', to: 'clients#update'
  
  # Client Booking
  get '/client/booking', to: 'bookings#book'
  post '/client/booking/check_cleaner', to: 'bookings#check_cleaner'
  post '/client/booking', to: 'bookings#create'
  

  # Cleaner Bookings
  get 'cleaner/bookings', to: 'cleaners#bookings'
  post '/cleaner/booking/:id', to: 'bookings#show', as: :cleaner_booking
  
  #Client Bookings
  get 'client/bookings', to: 'clients#bookings'

  #Cleaner edit password
  get 'cleaner/edit/password', to: 'cleaners#edit_password'
  post 'cleaner/edit/password', to: 'cleaners#change_password'

  #Client edit password
  get 'client/edit/password', to: 'clients#edit_password'
  post 'client/edit/password', to: 'clients#change_password'

  #Cleaner edit city
  match 'cleaner/edit/city', to: 'cleaners#edit_city', via: [:get, :post]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/client.rb
class Client < ApplicationRecord

  include Password
  
  has_many  :bookings 
  validates :fname, presence: true, length: { minimum: 2 }
  validates :lname, presence: true, length: { minimum: 2 }
  validates_format_of :email, with: /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

  before_save :password_to_md5

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  before_action :set_client
  before_action :authorize
  

  def edit
    
  end

  def edit_password

  end

  def change_password
    if @client.check_password? params[:pass][:old]
      if params[:pass][:new] == params[:pass][:repeat] 
        unless params[:pass][:new].empty? 
          @client.update_password params[:pass][:new]
          if @client.save
            redirect_to client_page_path
          else
            @notice = @client.errors.full_messages
            render 'edit_password' 
          end
        else
          @notice = ['new fields are empry']
          render 'edit_password'
        end  
      else
        @notice = ['new passwords do not match']
        render 'edit_password'
      end
    else
      @notice = ['invalid old password'] 
      render 'edit_password' 
    end
  end
  
  def update
    updates = client_params.delete_if { |k, val| val.empty? }
    if updates.empty?
      @notice = ['fields are empty']
      render 'edit'
    else
      if @client.update(updates)
        redirect_to client_page_path
      else
        @notice = @client.errors.full_messages
        render 'edit'
      end
    end
  end

  def destroy
    @client.destroy
    redirect_to logout_client_path
  end

  def page
   
  end

  def bookings
    @bookings = @client.bookings
  end

  private

  def set_client
    @client = Client.find_by_id(session[:client_id].to_i)
  end

  def client_params
    params.require(:user).permit(:fname, :lname, :email)
  end

  

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_tag client_edit_path do %>

  <h2>Edit Client</h2>

  <%= label_tag 'Fname:' %>
  
  <%= text_field_tag 'user[fname]' %> 

  <%= label_tag 'Lname:' %>
  <%= text_field_tag 'user[lname]' %>

  <%= label_tag 'Email:' %>

  <%= text_field_tag 'user[email]' %>


  <%= submit_tag :Edit, class: :btn%> 

  <% if @notice %>
    <div class="err">
      <% @notice.each do |error| %> 
        <%= ". #{error}" %><br>  
      <% end %>
    </div>
  <% end %>

  <%= link_to 'edit password', client_edit_password_path, class: :simple_link %>


<% end %> 

app/views/clients/bookings.html.erb
<% if @bookings.empty? %>
  <div class="err"> no bookings </div>
<% else %>
    <table class="book">
      <tr>
        <th>Cleaner Fname</th>
        <th>Cleaner Lname</th> 
        <th>Date</th>
        <th>Time</th>
      </tr>
	      <% @bookings.each_with_index do |book, i| %>
          <tr>
            <td><%= book.cleaner.fname %></td>
            <td><%= book.cleaner.lname %></td> 
            <td><%= book.date_to_s %></td>
            <td><%= book.time %></td>
          </tr>
        <% end %> 
  </table>
<% end %>

app/views/clients/edit.html.erb
<%= render 'form' %>

app/views/clients/edit_password.html.erb
<%= form_tag client_edit_password_path do %>

 <h2 style="margin-bottom: 15px; margin-top: 0">Edit Password</h2>
 
  <%= label_tag 'Old Pasword:' %>
  <%= text_field_tag 'pass[old]' %>

  <%= label_tag 'New Password:' %>
  <%= text_field_tag 'pass[new]' %>

  <%= label_tag 'Repeat Password:' %>
  <%= text_field_tag 'pass[repeat]' %>

  <%= submit_tag :Edit, class: :btn %> 

  <% if @notice %>
    <div class="err">
      <% @notice.each do |err| %>
        <%= ". #{err}" %><br>
      <% end %>
    </div>
  <% end %>

<% end %> 