config/routes.rb
Rails.application.routes.draw do

  # Home
  get '/home', to: 'home#welcome'

  # Admin
  match 'admin/filter/client', to: 'admin/filter#client_filter', via: [:get, :post]
  match 'admin/filter/cleaner', to: 'admin/filter#cleaner_filter', via: [:get, :post]

  # Registration
  get '/registration/client', to: 'registration#for_client'
  post '/registration/client', to: 'registration#create_client'
  get '/registration/cleaner', to: 'registration#for_cleaner'
  post '/registration/cleaner', to: 'registration#create_cleaner'
  
  # Login
  get '/login/client', to: 'sessions#for_client' 
  post '/login/client', to: 'sessions#create_client'
  get '/login/cleaner', to: 'sessions#for_cleaner' 
  post '/login/cleaner', to: 'sessions#create_cleaner'
  
  # Logout
  get '/logout_client', to: 'sessions#destroy_client'
  get '/logout_cleaner', to: 'sessions#destroy_cleaner'

  # Client Page
  get '/client/page', to: 'clients#page', as: :client_page
  get '/cleaner/page', to: 'cleaners#page', as: :cleaner_page
  
  # Client Delete
  delete '/client/delete', to: 'clients#destroy'
  
  #Cleaner Delete
  delete '/cleaner/delete', to: 'cleaners#destroy'

  # Client Edit 
  get '/cleaner/edit', to: 'cleaners#edit'
  post '/cleaner/edit', to: 'cleaners#update'

  #Cleaner Edit
  get '/client/edit', to: 'clients#edit'
  post '/client/edit', to: 'clients#update'
  
  # Client Booking
  get '/client/booking', to: 'bookings#book'
  post '/client/booking/check_cleaner', to: 'bookings#check_cleaner'
  post '/client/booking', to: 'bookings#create'
  

  # Cleaner Bookings
  get 'cleaner/bookings', to: 'cleaners#bookings'
  post '/cleaner/booking/:id', to: 'bookings#show', as: :cleaner_booking
  
  #Client Bookings
  get 'client/bookings', to: 'clients#bookings'

  #Cleaner edit password
  get 'cleaner/edit/password', to: 'cleaners#edit_password'
  post 'cleaner/edit/password', to: 'cleaners#change_password'

  #Client edit password
  get 'client/edit/password', to: 'clients#edit_password'
  post 'client/edit/password', to: 'clients#change_password'

  #Cleaner edit city
  match 'cleaner/edit/city', to: 'cleaners#edit_city', via: [:get, :post]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/cleaner.rb
class Cleaner < ApplicationRecord
 
  include Password

  has_many :bookings
  has_and_belongs_to_many :cities
  validates :fname, presence: true, length: { minimum: 2 }
  validates :lname, presence: true, length: { minimum: 2 }
  validates_format_of :email, with: /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

  before_save :password_to_md5

  scope :search_cleaner, -> (options = {})  do
 
  	cleaners = Cleaner.all
  	  
  	if options[:patterns].present?
      patterns = options[:patterns].downcase.split(' ').map! { |t| "#{t}%" } 
      field_names, query = ['fname', 'lname', 'email'], []
      patterns.length.times do |i|
        query[i] = "#{field_names[i]} LIKE ?"
      end
      cleaners = cleaners.where(query.join(' AND '), *patterns)
    end

    unless options[:cities].empty? 
      cleaners = cleaners.joins(:cities).where(cities: {id: options[:cities]}).distinct
    end

    if options[:date].present?
    	cleaners = cleaners.joins(:bookings).where(bookings: {date: options[:date]}).distinct
    end

    cleaners
    
  end



end

app/controllers/admin/filter_controller.rb
class Admin::FilterController < AdminController

	def client_filter

	  if params[:client]
      query, with = [], []
	  	client_hash.each do |key, val|
	  		unless  val.empty?
          query << "#{key} LIKE ?"
          with << "#{val}%" 
        end
	  	end
	  	@clients = Client.where(query.join(' AND '), *with)
 	  end

  end

	def cleaner_filter
		@cities = City.all
		@cleaners = Cleaner.all

    if params[:cleaner]

     patterns = ''
     cleaner_params.each { |k, v| patterns += "#{v} " if v.present? }

     cities = params[:city_ids] ? params[:city_ids].map(&:to_i) : []

     date = params[:booking_date].present? ? book_date : '' 

     @cleaners = Cleaner.search_cleaner(patterns: patterns, cities: cities, date: date)

	end

    end

	def booking_filter
	  @bookings = Bookings.all
    end

	def city_filter
		
	end

	def client_hash
		params.require(:client).permit(:fname, :lname, :email)
	end

  def cleaner_params
		params.require(:cleaner).permit(:fname, :lname, :email)
	end

	def book_date
		data = params[:booking_date].split '.'
    return "#{data[2]}-#{data[1]}-#{data[0]}"
	end

end

app/views/admin/filter/cleaner_filter.html.erb
<h1>Cleaner Filter</h1>

<div style="font-size: 17px">Filter by:</div><br>

<%= form_tag  admin_filter_cleaner_path do %>
  <%= label_tag :Fname %>
  <%= text_field_tag 'cleaner[fname]' %><br><br>

  <%= label_tag :Lname %>
  <%= text_field_tag 'cleaner[lname]' %><br><br>

  <%= label_tag :Email %>
  <%= text_field_tag 'cleaner[email]' %><br><br>

  <%= label_tag 'Booking Date' %>
  <%= text_field_tag 'booking_date' %><br><br>

  <% @cities.each do |city| %>
    <%= label_tag city.name, nil %>
    <%= check_box_tag 'city_ids[]', city.id %>
  <% end %>

  <div style="margin-top: 15px"><%= submit_tag :Filter %></div>
<% end %>

<% if @cleaners %>
  <p style="font-size: 16px">Finds Cleaners</p>
  <% if @cleaners.empty? %>
    <p style="color: red">not results</p>
  <% else %>
   	<table>
    	<tr>
	    	<th>Fname</th>
	    	<th>Lname</th>
		  	<th>Email</th>
   	  </tr>
  		<% @cleaners.each do |cleaner|%>
	    	<tr>
      		<td><%= cleaner.fname %></td>
      		<td><%= cleaner.lname %></td>
      		<td><%= cleaner.email %></td>
    		</tr>
    	<% end %>
		</table>
	<% end %>
<% end %>

app/views/admin/filter/client_filter.html.erb
<h1>Client Filter</h1>

<div style="font-size: 17px">Filter by:</div><br>

<%= form_tag  admin_filter_client_path do %>
  <%= label_tag :Fname %>
  <%= text_field_tag 'client[fname]' %><br><br>

  <%= label_tag :Lname %>
  <%= text_field_tag 'client[lname]' %><br><br>

  <%= label_tag :Email %>
  <%= text_field_tag 'client[email]' %><br><br>

  <%= submit_tag :Filter %>
<% end %><br><br>

<% if @clients %>
  <p style="font-size: 16px">Finds Clients</p>
  <% if @clients.empty? %>
    <p style="color: red">not results</p>
  <% else %>
    <table>
  		<tr>
	  	  <th>Fname</th>
				<th>Lname</th>
				<th>Email</th>
  		</tr>
  		<% @clients.each do |client|%>
	  		<tr>
      		<td><%= client.fname %></td>
      		<td><%= client.lname %></td>
      		<td><%= client.email %></td>
    		</tr>
  		<% end %>
  	</table>
	<% end %>
<% end %>