config/routes.rb
Rails.application.routes.draw do

  # Home
  get '/home', to: 'home#welcome'

  # Admin
  match 'admin/filter/client', to: 'admin/filter#client_filter', via: [:get, :post]
  match 'admin/filter/cleaner', to: 'admin/filter#cleaner_filter', via: [:get, :post]

  # Registration
  get '/registration/client', to: 'registration#for_client'
  post '/registration/client', to: 'registration#create_client'
  get '/registration/cleaner', to: 'registration#for_cleaner'
  post '/registration/cleaner', to: 'registration#create_cleaner'
  
  # Login
  get '/login/client', to: 'sessions#for_client' 
  post '/login/client', to: 'sessions#create_client'
  get '/login/cleaner', to: 'sessions#for_cleaner' 
  post '/login/cleaner', to: 'sessions#create_cleaner'
  
  # Logout
  get '/logout_client', to: 'sessions#destroy_client'
  get '/logout_cleaner', to: 'sessions#destroy_cleaner'

  # Client Page
  get '/client/page', to: 'clients#page', as: :client_page
  get '/cleaner/page', to: 'cleaners#page', as: :cleaner_page
  
  # Client Delete
  delete '/client/delete', to: 'clients#destroy'
  
  #Cleaner Delete
  delete '/cleaner/delete', to: 'cleaners#destroy'

  # Client Edit 
  get '/cleaner/edit', to: 'cleaners#edit'
  post '/cleaner/edit', to: 'cleaners#update'

  #Cleaner Edit
  get '/client/edit', to: 'clients#edit'
  post '/client/edit', to: 'clients#update'
  
  # Client Booking
  get '/client/booking', to: 'bookings#book'
  post '/client/booking/check_cleaner', to: 'bookings#check_cleaner'
  post '/client/booking', to: 'bookings#create'
  

  # Cleaner Bookings
  get 'cleaner/bookings', to: 'cleaners#bookings'
  post '/cleaner/booking/:id', to: 'bookings#show', as: :cleaner_booking
  
  #Client Bookings
  get 'client/bookings', to: 'clients#bookings'

  #Cleaner edit password
  get 'cleaner/edit/password', to: 'cleaners#edit_password'
  post 'cleaner/edit/password', to: 'cleaners#change_password'

  #Client edit password
  get 'client/edit/password', to: 'clients#edit_password'
  post 'client/edit/password', to: 'clients#change_password'

  #Cleaner edit city
  match 'cleaner/edit/city', to: 'cleaners#edit_city', via: [:get, :post]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CleaningBoard</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body style="padding-left: 50px; padding-right: 50px">
    <div style="background: #ccc;  padding: 10px">
      <span style="font-size: 22px; margin-right: 25px">ADMIN</span>
        <%=  link_to("back", request.referer, class: :link) %>     </div>
    <%= yield %>
  </body>
</html> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CleaningBoard</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 
  <body>

    <div class="menu">
      <div class="title">
        <span class="sp">Cleaning Board</span>
      </div>
      <div class="side">
        <%=  link_to("back", request.referer, class: :link) %> 
      </div>
    </div>
    <div class="container">
      <%= yield %>
    </div>

  </body>


</html>

app/views/layouts/bookings.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cleaning Board</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'bookings', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 
  <body>
      <div class="menu_panel">
      <div class="logo">
        <span>Cleaning Board</span> 
      </div>
      <div class="menu"> 
        <%= link_to "my page", client_page_path, class: :link %> 

        <%= link_to "booking", client_booking_path, class: :link %>

        <%=  link_to "my bookings", client_bookings_path, method: :get, class: :link %>

        <%=  link_to "edit", client_edit_path, class: :link %> 

        <%=  link_to "destroy", client_delete_path, method: :delete, data: {confirm: 'are you want delete your profile?'}, class: :link %>

        <%= link_to "logout", logout_client_path, class: :link, data: {confirm: 'Do you want to get out?'} %>

        <%=  link_to "back", request.referer, class: :link %> 
         
      </div>
    </div>

    <div class="container">
    <!-- <div style="color: #ddd; font-size: 18px"><%= request.referer %></div> -->
      <%= yield %>
    </div>
    

  </body>


</html>

app/views/layouts/cleaners.html.erb
<!DOCTYPE html>
<html>
  <!DOCTYPE html>
<html>
  <head>
    <title>Cleaning Board</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="menu">
      <div class="title">
        <span class="sp">Cleaning Board</span>
      </div>
      <div class="side">

        <%=  link_to "main page", cleaner_page_path, class: :link %>  

        <%= link_to "my bookings", cleaner_bookings_path, method: :get, class: :link %> 

        <%=  link_to "edit", cleaner_edit_path, method: :get, class: :link %> 

        <%=  link_to "destroy", cleaner_delete_path, method: :delete, data: {confirm: 'are you want delete your profile?'}, class: :link %> 
        
        <%= link_to "logout", logout_cleaner_path, class: :link %>
        
        <%=  link_to "back", request.referer, class: :link %> 

      </div>
    </div>

    <div class="container">
      <%= yield %>

    </div>

  </body>

  
</html>

app/views/layouts/clients.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cleaning Board</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'clients', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 
  <body>
      <div class="menu_panel">
      <div class="logo">
        <span>Cleaning Board</span>
      </div>
      <div class="menu"> 
        <%= link_to "my page", client_page_path, class: :link %> 

        <%= link_to "booking", client_booking_path, class: :link %>

        <%=  link_to "my bookings", client_bookings_path, method: :get, class: :link %>

        <%=  link_to "edit", client_edit_path, class: :link %> 

        <%=  link_to "destroy", client_delete_path, method: :delete, data: {confirm: 'are you want delete your profile?'}, class: :link %>

        <%= link_to "logout", logout_client_path, class: :link, data: {confirm: 'Do you want to get out?'} %>
        
        <%=  link_to "back", request.referer, class: :link %> 


      </div>
    </div>

    <div class="container">
        <!-- <div style="color: #ddd; font-size: 18px"><%= request.referer %></div> -->

      <%= yield %>
    </div>
    

  </body>


</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CleaningBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'home', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 
  <body>

    <div class="menu_panel">
      <div class="logo">
        <span>Cleaning Board</span> 
      </div>
      <div class="menu"> 
        <%= link_to 'login client', login_client_path, class: :link %> 
        <%= link_to 'login cleaner', login_cleaner_path, class: :link %> 
        <%= link_to 'registration client', registration_client_path, class: :link %>
        <%= link_to 'registration cleaner', registration_cleaner_path, class: :link %>        
      </div>
    </div>

       
          
        
      
    <div class="container">
      <%= yield %>
    </div>

  </body>
  
</html>

app/views/layouts/registration.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CleaningBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'registration', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 
  <body>
  
    <div class="menu_panel">
      <div class="logo">
        <span>Cleaning Board</span>
      </div>
      <div class="menu"> 
        <%= link_to 'login client', login_client_path, class: :link %> 
        <%= link_to 'login cleaner', login_cleaner_path, class: :link %> 
        <%= link_to 'registration client', registration_client_path, class: :link %>
        <%= link_to 'registration cleaner', registration_cleaner_path, class: :link %>   
        <%=  link_to("back", request.referer, class: :link) %>       </div>
    </div>

    <div class="container">
      <%= yield %>
    </div>
    
  </body>


</html>

app/views/layouts/sessions.html.erb
 <!DOCTYPE html>
<html>
  <head>
    <title>CleaningBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'sessions', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 
  <body>
  
    <div class="menu_panel">
      <div class="logo">
        <span>Cleaning Board</span>
      </div>
      <div class="menu"> 
        <%= link_to 'login client', login_client_path, class: :link %> 
        <%= link_to 'login cleaner', login_cleaner_path, class: :link %> 
        <%= link_to 'registration client', registration_client_path, class: :link %>
        <%= link_to 'registration cleaner', registration_cleaner_path, class: :link %>   
       <%=  link_to("back", request.referer, class: :link) %> 
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div>
    
  </body>


</html>